apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: safe_redirect
  description: Elixir library to validate redirect URLs

spec:
  type: library
  businessUnit: hr
  public: true
  lifecycle: production
  owner: group:default/poblano
  github:
    team: poblano
  technologies:
    - elixir
  capabilities:
    - redirect-url-resolution
