name: CI

env:
  ELIXIR_VERSION: "1.20.2"
  OTP_VERSION: "28"

on:
  push:

jobs:
  test-elixir:
    name: Elixir tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}
      - name: Restore dependencies and build cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
      - name: Restore PLT cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        id: plt_cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plt-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plt-
          path: |
            .plts
      - name: Authenticate with Hex
        run: mix hex.organization auth scoville --key ${{ secrets.HEX_ORGANIZATION_KEY }}
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Hex Audit
        run: mix hex.audit
      - name: Run Formatter
        run: mix format --check-formatted
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Run Linter
        run: mix credo
      - name: Build documentation
        run: mix docs --warnings-as-errors
      - name: Run Tests
        run: mix coveralls.html
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - name: Run Dialyzer
        run: mix dialyzer --format github
