name: Publish

env:
  ELIXIR_VERSION: "1.18.4"
  OTP_VERSION: "27"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish Hex package
    runs-on: ubuntu-24.04
    steps:
      - name: Git clone the repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Restore dependencies and build cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-mix-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-

      - name: Install Hex and Rebar
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: Install Dependencies
        run: mix deps.get

      - name: Authenticate with Hex
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_PUBLISH_KEY }}
